export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"

plugins=(
  git
  zsh-autosuggestions
  zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

alias ls='exa --icons'
alias ll='exa -l --icons'
alias la='exa -la --icons'

alias cat='bat -f'

alias paci='yay -Slq | fzf --multi --preview "yay -Si {1}" | xargs -ro yay -S'
alias pacm='yay -Syy'
alias pacu='yay -Syyuu'
alias pacr='yay -Qeq | fzf --multi --preview "yay -Si {1}" | xargs -ro yay -Rns'
